#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.workflow.validate_modern_docx_omml import DEFAULT_INVENTORY, inspect_docx, read_json


DEFAULT_JAR = ROOT / "target" / "docx-html-math-1.0.0-jar-with-dependencies.jar"
DEFAULT_OUTPUT_ROOT = ROOT / "out" / "modern-docx-omml-generated"
DEFAULT_CASE_IDS = [
    "modern_inline_omml_sample",
    "modern_block_omml_sample",
    "modern_mixed_block_inline_sample",
    "modern_supported_multi_equation_paragraph",
]


def _computed_placement_summary(inline_omath_count: int, omathpara_count: int) -> str:
    if inline_omath_count > 0 and omathpara_count > 0:
        return f"mixed inline/block OMML: inline_oMath={inline_omath_count} oMathPara={omathpara_count}"
    if inline_omath_count > 0:
        return f"inline OMML only: inline_oMath={inline_omath_count}"
    if omathpara_count > 0:
        return f"block OMML only: oMathPara={omathpara_count}"
    return "no OMML math"


def _case_index(inventory_path: Path) -> Dict[str, Dict[str, Any]]:
    inventory = read_json(inventory_path)
    cases = inventory.get("cases", [])
    if not isinstance(cases, list):
        raise ValueError("inventory cases must be a list")
    return {
        str(case.get("case_id", "")).strip(): case
        for case in cases
        if isinstance(case, dict) and str(case.get("case_id", "")).strip()
    }


def _repo_relative(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path.resolve())


def _source_path(case: Dict[str, Any]) -> Path:
    source_docx = str(case.get("source_docx", "")).strip()
    if not source_docx:
        raise ValueError(f"case {case.get('case_id', '')} has no source_docx")
    path = Path(source_docx)
    return path if path.is_absolute() else ROOT / path


def build_manifest_case(case: Dict[str, Any], output_docx: Path) -> Dict[str, Any]:
    expected = case.get("expected", {})
    if not isinstance(expected, dict):
        expected = {}
    source_inspection = inspect_docx(_source_path(case))
    equation_count = int(expected.get("equation_count", 0) or 0)
    block_count = int(expected.get("block_equation_count", 0) or 0)
    inline_count = int(expected.get("inline_equation_count", 0) or 0)
    return {
        "case_id": f"{case['case_id']}_generated_output",
        "source_case_id": case["case_id"],
        "source_docx": str(case.get("source_docx", "")),
        "generated_docx": output_docx.name,
        "classification": "supported",
        "expected": {
            "document_xml_exists": True,
            "document_xml_parseable": True,
            "equation_count": equation_count,
            "block_equation_count": block_count,
            "inline_equation_count": inline_count,
            "appears_inline_math": inline_count > 0,
            "appears_block_math": block_count > 0,
            "basic_omml_structure_present": equation_count > 0 or block_count > 0,
            "computed_placement_summary": _computed_placement_summary(inline_count, block_count),
            "valid_omath_omathpara_structure": True,
            "inline_paragraph_run_context_safe": bool(source_inspection.get("inline_paragraph_run_context_safe")),
            "block_omathpara_context_safe": bool(source_inspection.get("block_omathpara_context_safe")),
            "surrounding_non_math_text_preserved": bool(source_inspection.get("surrounding_non_math_text_preserved")),
            "paragraph_run_safety_summary": str(source_inspection.get("paragraph_run_safety_summary", "unavailable")),
        },
        "notes": [
            "generated by the current modern DOCX --patch-docx path",
            "used as a generated-output precondition before product behavior changes",
        ],
    }


def run_patch_docx(jar: Path, source_docx: Path, output_docx: Path) -> str:
    output_docx.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "java",
        "-jar",
        str(jar),
        "--patch-docx",
        str(source_docx),
        str(output_docx),
        "--patch-log-level",
        "summary",
    ]
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or proc.stdout.strip() or f"patch command failed: {source_docx}")
    return proc.stdout


def generate_manifest(
    inventory_path: Path,
    case_ids: List[str],
    output_root: Path,
    jar: Path,
    manifest_name: str,
) -> Dict[str, Any]:
    if not jar.exists():
        raise FileNotFoundError(f"Jar not found: {jar}")

    cases_by_id = _case_index(inventory_path)
    manifest_cases = []
    generated_outputs = []
    for case_id in case_ids:
        if case_id not in cases_by_id:
            raise ValueError(f"case not found in inventory: {case_id}")
        case = cases_by_id[case_id]
        if str(case.get("classification", "")).strip() != "supported":
            raise ValueError(f"case is not supported modern DOCX: {case_id}")
        source_docx = _source_path(case)
        if not source_docx.exists():
            raise FileNotFoundError(f"source DOCX not found for {case_id}: {source_docx}")
        output_docx = output_root / f"{case_id}.generated.docx"
        run_patch_docx(jar, source_docx, output_docx)
        generated_outputs.append(output_docx)
        manifest_cases.append(build_manifest_case(case, output_docx))

    manifest = {
        "schema_version": "modern_docx_omml_generated_outputs.v1",
        "description": "Generated modern DOCX + OMML output manifest produced by the current --patch-docx path.",
        "source_inventory": _repo_relative(inventory_path),
        "generated_output_root": _repo_relative(output_root),
        "cases": manifest_cases,
    }
    output_root.mkdir(parents=True, exist_ok=True)
    manifest_path = output_root / manifest_name
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    manifest["manifest_path"] = str(manifest_path)
    manifest["generated_outputs"] = [str(path) for path in generated_outputs]
    return manifest


def parse_args(argv: Optional[Iterable[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a small generated-output manifest from the modern DOCX + OMML path."
    )
    parser.add_argument("--inventory", type=Path, default=DEFAULT_INVENTORY)
    parser.add_argument("--case", action="append", dest="cases", default=[], help="Modern inventory case_id to generate.")
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--jar", type=Path, default=DEFAULT_JAR)
    parser.add_argument("--manifest-name", default="modern_docx_omml_generated_outputs.json")
    return parser.parse_args(argv)


def main(argv: Optional[Iterable[str]] = None) -> int:
    args = parse_args(argv)
    case_ids = args.cases or DEFAULT_CASE_IDS
    try:
        manifest = generate_manifest(
            inventory_path=args.inventory.resolve(),
            case_ids=case_ids,
            output_root=args.output_root.resolve(),
            jar=args.jar.resolve(),
            manifest_name=args.manifest_name,
        )
    except (FileNotFoundError, RuntimeError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 1

    print("Modern DOCX + OMML generated-output manifest")
    print(f"Manifest: {manifest['manifest_path']}")
    print("Generated outputs:")
    for path in manifest["generated_outputs"]:
        print(f"- {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
