package com.example.docxmath.word;

public enum PatchSkipReason {
    NATIVE_OMML_PRESENT,
    DRAWING_IN_RUN,
    LAST_RENDERED_PAGE_BREAK_IN_RUN,
    MULTIPLE_OBJECTS_IN_SINGLE_RUN,
    MIXED_OBJECT_AND_TEXT_IN_RUN,
    UNSUPPORTED_PARAGRAPH_CHILD,
    UNKNOWN_SOURCE_KIND,
    AMBIGUOUS_SEGMENT_SEQUENCE,
    UNRESOLVED_MANIFEST,
    OMML_CONVERSION_FAILED,
    XML_MUTATION_ROLLBACK,
    OTHER_UNSAFE_MODEL
}
