package com.example.docxmath;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Maps original DOCX part names (for example /word/media/image12.wmf or /word/embeddings/oleObject3.bin)
 * to pre-converted MathML sidecar files generated by an external tool such as transpect mathtype-extension.
 */
public final class MathmlSidecarRegistry {
    private final Map<String, Path> byPartName = new HashMap<>();
    private final Map<String, Path> byLeafName = new HashMap<>();
    private final Map<Path, String> mathmlTextCache = new HashMap<>();

    private MathmlSidecarRegistry() {
    }

    public static MathmlSidecarRegistry empty() {
        return new MathmlSidecarRegistry();
    }

    public static MathmlSidecarRegistry load(Path manifestFile) throws IOException {
        MathmlSidecarRegistry registry = new MathmlSidecarRegistry();
        if (manifestFile == null || !Files.exists(manifestFile)) {
            return registry;
        }

        Path baseDir = manifestFile.toAbsolutePath().normalize().getParent();
        List<String> lines = Files.readAllLines(manifestFile, StandardCharsets.UTF_8);
        for (String raw : lines) {
            String line = raw == null ? "" : raw.trim();
            if (line.isEmpty() || line.startsWith("#")) {
                continue;
            }
            String[] parts = line.split("\t", 2);
            if (parts.length != 2) {
                continue;
            }
            String partName = normalizePartName(parts[0]);
            Path mathmlFile = baseDir.resolve(parts[1]).normalize();
            registry.byPartName.put(partName, mathmlFile);
            registry.indexLeafName(partName, mathmlFile);
        }
        return registry;
    }

    public boolean hasMathmlForPart(String partName) {
        return resolveMathmlPath(partName) != null;
    }

    public String readMathmlForPart(String partName) throws IOException {
        Path p = resolveMathmlPath(partName);
        if (p == null) {
            return null;
        }
        if (mathmlTextCache.containsKey(p)) {
            return mathmlTextCache.get(p);
        }
        if (!Files.exists(p)) {
            mathmlTextCache.put(p, null);
            return null;
        }
        String text = Files.readString(p, StandardCharsets.UTF_8).trim();
        if (text.isBlank()) {
            text = null;
        }
        mathmlTextCache.put(p, text);
        return text;
    }

    private void indexLeafName(String partName, Path mathmlFile) {
        String leafName = leafName(partName);
        if (leafName.isEmpty()) {
            return;
        }
        Path existing = byLeafName.get(leafName);
        if (existing == null) {
            byLeafName.put(leafName, mathmlFile);
            return;
        }
        if (!existing.equals(mathmlFile)) {
            byLeafName.put(leafName, null);
        }
    }

    private Path resolveMathmlPath(String partName) {
        String normalized = normalizePartName(partName);
        Path exact = byPartName.get(normalized);
        if (exact != null) {
            return exact;
        }
        String leafName = leafName(normalized);
        if (leafName.isEmpty()) {
            return null;
        }
        return byLeafName.get(leafName);
    }

    private static String normalizePartName(String partName) {
        String s = Objects.toString(partName, "").trim().replace('\\', '/');
        int queryIndex = s.indexOf('?');
        if (queryIndex >= 0) {
            s = s.substring(0, queryIndex);
        }
        if (!s.startsWith("/")) {
            s = "/" + s;
        }
        return s;
    }

    private static String leafName(String partName) {
        String normalized = normalizePartName(partName);
        int slash = normalized.lastIndexOf('/');
        return slash >= 0 ? normalized.substring(slash + 1) : normalized;
    }
}
